### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by mmacadamsphonecom** [braceslab/service-systemd#3]
Just a heads up, I'm getting the following error report when trying to use this.

Ubuntu 16.04
NodeJS version: 4.2.6

Thanks!

root@someserver:/opt/repos/awesomerepo# service-systemd --help
/usr/local/lib/node_modules/service-systemd/node_modules/a-toolbox/index.js:296
      let _properties
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/service-systemd/node_modules/log-segment/main.js:3:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by simone-sanfratello** [comment]
Thanks for report the issue, I had fixed the problem

please reinstall and try again
``npm i -g service-systemd``
