### ISSUE TITLE
Engine default not set

### ISSUE THREAD

**Issue by FallingSnow** [braceslab/service-systemd#8]
If I don't set the engine parameter in the settings I get:
```js
Error: Missing engine in settings file or arguments                                                                                                        
    at Promise ([redacted]/node_modules/service-systemd/lib/setup.js:197:16)                                                                                                           
    at Promise._execute ([redacted]/node_modules/bluebird/js/release/debuggability.js:303:9)                                                                                           
    at Promise._resolveFromExecutor ([redacted]/node_modules/bluebird/js/release/promise.js:483:18)                                                                                    
    at new Promise ([redacted]/node_modules/bluebird/js/release/promise.js:79:10)                                                                                                      
    at Object.setup.checkSettings ([redacted]/node_modules/service-systemd/lib/setup.js:186:10)                                                                                        
    at Promise ([redacted]/node_modules/service-systemd/lib/setup.js:85:11)                                                                                                            
    at Promise._execute ([redacted]/node_modules/bluebird/js/release/debuggability.js:303:9)                                                                                           
    at Promise._resolveFromExecutor ([redacted]/node_modules/bluebird/js/release/promise.js:483:18)                                                                                    
    at new Promise ([redacted]/node_modules/bluebird/js/release/promise.js:79:10)                                                                                                      
    at Object.setup.add ([redacted]/node_modules/service-systemd/lib/setup.js:81:10)                                                                                                   
    at main ([redacted]/index.js:40:35)                                                                                                                                                
    at Object.<anonymous> ([redacted]/index.js:62:3)                                                                                                                                   
    at Module._compile (internal/modules/cjs/loader.js:707:30)                                                                                                                                                    
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)                                                                                                                                      
    at Module.load (internal/modules/cjs/loader.js:605:32)                                                                                                                                                        
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
```

Isn't engine supposed to default to node without me having to set it?

**Comment by simone-sanfratello** [comment]
Could you please add settings that cause this issue?
